// Authors: Aidan Lethaby and Sean Richens, November 2019
// Projectile for CS 3500 TankWars game
// University of Utah

using Newtonsoft.Json;
using TankWars;

namespace Model
{
    /// <summary>
    /// This class represents projectiles for our TankWars game
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class Projectile : IHasID
    {
        /// <summary>
        /// Unique identifier of the projectile.
        /// </summary>
        [JsonProperty(PropertyName = "proj")]
        public int ID { get; set; }

        /// <summary>
        /// Location of the projectile in the world.
        /// </summary>
        [JsonProperty(PropertyName = "loc")]
        public Vector2D Location { get; set; }

        /// <summary>
        /// Direction of travel of the projectile in the world.
        /// </summary>
        [JsonProperty(PropertyName = "dir")]
        public Vector2D Orientation { get; set; }

        /// <summary>
        /// State of the powerup.
        /// True if projectile has hit another object.
        /// </summary>
        [JsonProperty(PropertyName = "died")]
        public bool Died { get; set; }

        /// <summary>
        /// The player who fired the projectile.
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public int Owner { get; set; }

        /// <summary>
        /// The default constructor for the prijectile class
        /// </summary>
        public Projectile()
        {
            Died = false;
        }

        /// <summary>
        /// A counter for ID's generated by the server
        /// </summary>
        private static int nextID = 0;

        public Projectile(int iD, Vector2D location, Vector2D orientation)
        {
            Owner = iD;
            Location = location;
            Orientation = orientation;
            Died = false;
            ID = nextID++;
        }
    }
}